### PR TITLE
Only show Achievements if certain plugins are active

### PR DESCRIPTION
**Pull request by BronsonQuick**
Hey Paul,

Firstly, great work on Achievements. I'm amazed by how much work you've done in 3.0+ :)

I'm currently doing some prototyping for a potential job and thought that it from a UI point of view it would make more sense to only show achievements for a plugin if it's activated.

In my first pass I checked if plugins were active in the "Plugin extensions" section of achievements.php but then I realised that if I did that it broke the Supported Plugins section of Achievements.

This is my second pass which fixes that problem by tackling it in a different way. It looks like there is some whitespace issues in the patch...I blame PhpStorm & Windows for that :)

Hopefully you can sneak this in 3.3 if you haven't shipped it yet :)

I've attached some screenshots to show my testing as well. Hopefully we'll get this job too and I'll be able to add loads more patches!

BuddyPress and WordPress are active
Supported Plugins Page
Supported Features Page Without bbPress Activated
Supported Features Page When bbPress Isn't Installed

I hope you're having fun working in VIP too :+1: 

Cheers!

### CODE REVIEW

**Comment by BronsonQuick** [comment]
P.S. Apologies for https://github.com/BronsonQuick/achievements/commit/169df067ad556fa486df2f11d6aec79b1f3a2a6f and https://github.com/BronsonQuick/achievements/commit/58f0492e09bd742dc7db99fab341b3a034b0b205

I should branched before I started working on it ;)

**Comment by paulgibbs** [comment]
Howdy, Bronson. Thanks!
This commit looks really very good, and the change is a great improvement which has been implemented smartly. My only feedback is the $_GET checks, e.g.

"if ( is_plugin_active( 'wp-e-commerce/wp-shopping-cart.php' ) || ( 'achievements-plugins' == $_GET['page'] ))"
- $_GET['page'] may not be set, and thus cause a PHP Notice.
- $_GET['page'] may be set on the frontend, where we only want to check in the backend.

Changing these comparisons to something like the following would be a good improvement:

"if ( is_plugin_active( 'wp-e-commerce/wp-shopping-cart.php' ) || ( is_admin() && isset( $_GET['page'] ) &&  'achievements-plugins' == $_GET['page'] ))"

Are you able to make these improvements to your branch?

**Comment by BronsonQuick** [comment]
Ahh good thinking Sir! I hadn't thought of that. I'll try and get to that when I get home tonight.

P.S. It looks like we've landed that job you referred to us as well so hopefully I'll have some more pull requests with some features in a few weeks!

**Comment by BronsonQuick** [comment]
Alrighty. I've added those in now Paul. I didn't realise I didn't have WP_DEBUG set to true on that test branch otherwise I would've picked up on those Undefined indexes.

Thanks for shooting through the lead for us as well :+1: I'm looking forward to getting stuck into it next week!

**Comment by paulgibbs** [comment]
You're welcome! Thanks again for the patch.

**Comment by vfowler** [comment]
Thanks @BronsonQuick @paulgibbs You guys rock my world.

**Comment by paulgibbs** [comment]
I had to revert these changes. If Achievements was activated before a supported plugin was, get_actions() returned an empty array, so no tax items were added, and as that extension's ID is stored in the 'versions' option, the automatic install doesn't reoccur on the next page load.

If a supported plugin was activated _before_ Achievements was, everything worked fine.

I wanted to do something like the following, but as we do this stuff before get_current_screen() is loaded, it wasn't particularly easy or elegant to re-implement this:

```
if ( is_plugin_active( 'wp-postratings/wp-postratings.php' ) || is_admin() && ( in_array( get_current_screen()->id, array( 'plugins', 'plugins-network' ) ) || ( isset( $_GET['page'] ) && 'achievements-plugins' == $_GET['page'] ) ) ) {
```

**Comment by BronsonQuick** [comment]
Damn me! #blamebronson :grin: 

I actually got a bit stuck with the $this->version last week when I was coding up a new custom achievement for a plugin of ours. I realised @rmccue had the same issue as I did as well.

I think I'll probably need to get my head around what you're doing with $this->version for extensions before I help with this. #bronsonsucks

**Comment by paulgibbs** [comment]
Putting into 3.6 as this was pretty close to perfect, so let's figure it out.

**Pull request merged**
