### PR TITLE
Achievement Admin Page With Thumbnails

### PR DESCRIPTION
**Pull request by mikebronner**
Added filter and action to insert achievement thumbnail on the achievements admin page. Customizations includes thumbnail size, column position, and header title.

Image width or height is constrained to no more than 39px so as to not alter the height of item rows. However, should this size prove to be to small, it can easily be adjusted.

### CODE REVIEW

**Comment by paulgibbs** [comment]
If you make the changes in the same branch, this pull request will update itself. I don't mind seeing reasonable amounts of interim commits as it shows how a piece of code evolves. (I'd have merged this commit in already, and be happy to iterate on it, if I had a better grasp of branching, as I mentioned in your other ticket!).

**Comment by mikebronner** [comment]
I'm learning as I go here as well. :) I'll have the updates shortly.

**Comment by mikebronner** [comment]
OK, should be updated now. :) :+1:

**Comment by paulgibbs** [comment]
It's in! Thanks for the patch, Mike! :D

**Pull request closed without merging**
