### PR TITLE
Leaderboard Function

### PR DESCRIPTION
**Pull request by mikebronner**
Added function that can return the ranking for the current user, or a list of rankings for all users, limited by default to a single page at a time. This can be overridden if needed by setting $posts_per_page to a very high number.

### CODE REVIEW

**Comment by paulgibbs** [comment]
First of all, we need to figure out if/how well this SQL query is actually going to scale. Any thoughts on how we can do this? Write a script to fill up a DB with a bunch of dummy data, and do some time tests?

**Comment by mikebronner** [comment]
Yea, we'd need to create oodles of users and assign them random karma points. I guess we should test 100, 500, 1000, 5000, 10000, and 20000 users?

**Comment by mikebronner** [comment]
What should we have as test parameters?
- Fresh install of Wordpress using TwentyTwelve theme
- incremental number of users
  anything else?

**Comment by mikebronner** [comment]
Here are some results. What do you think? Scalability appears to be pretty linear on the main query to list all users. Surprisingly, the solution you suggested for getting the ranking on the current user seems to scale exceptionally well.

# 1 User

Time to fetch one ranked row for current user with 100 attempts:
    Average: 0.000323865413666
    Min: 0.000309944152832
    Max: 0.000519990921021
    Total: 0.0323865413666
Time to fetch one page of all users with 100 attempts: 
    Average: 0.000194818973541
    Min: 0.000191926956177
    Max: 0.00019907951355
    Total: 0.0194818973541

# 100 Users

Time to fetch one ranked row for current user with 100 attempts:
    Average: 0.000301289558411
    Min: 0.000284910202026
    Max: 0.00036883354187
    Total: 0.0301289558411
Time to fetch one page of all users with 100 attempts:
    Average: 0.000399761199951
    Min: 0.000257968902588
    Max: 0.000548124313354
    Total: 0.0399761199951

# 500 Users

Time to fetch one ranked row for current user with 100 attempts:
    Average: 0.000312306880951
    Min: 0.000298023223877
    Max: 0.000331878662109
    Total: 0.0312306880951
Time to fetch one page of all users with 100 attempts:
    Average: 0.0575305533409
    Min: 0.0567970275879
    Max: 0.0626060962677
    Total: 5.75305533409

# 1500 Users

Time to fetch one ranked row for current user with 100 attempts:
    Average: 0.000312027931213 
    Min: 0.00029993057251
    Max: 0.00035285949707
    Total: 0.0312027931213
Time to fetch one page of all users with 100 attempts:
    Average: 0.167186529636
    Min: 0.165693044662
    Max: 0.174437999725
    Total: 16.7186529636

# 5000 Users

Time to fetch one ranked row for current user with 100 attempts:
    Average: 0.000325660705566
    Min: 0.000312089920044
    Max: 0.000381946563721
    Total: 0.0325660705566
Time to fetch one page of all users with 100 attempts:
    Average: 0.560528736115
    Min: 0.555218219757
    Max: 0.661763906479
    Total: 56.0528736115

# 10102 Users

Time to fetch one ranked row for current user with 100 attempts:
    Average: 0.000309851169586
    Min: 0.000298023223877
    Max: 0.00036096572876
    Total: 0.0309851169586
Time to fetch one page of all users with 100 attempts:
    Average: 1.1599576211
    Min: 1.14222192764
    Max: 1.35492897034
    Total: 115.99576211

# 20057 Users

Time to fetch one ranked row for current user with 100 attempts:
    Average: 0.000322690010071
    Min: 0.000284910202026
    Max: 0.000576972961426
    Total: 0.0322690010071
Time to fetch one page of all users with 100 attempts:
    Average: 2.89920308352
    Min: 2.79761099815
    Max: 3.93713092804
    Total: 289.920308352

**Comment by paulgibbs** [comment]
Can you share your test script?

**Comment by mikebronner** [comment]
Absolutely :) It's actually more of a process than a script, but doable:

1) Fresh install of WP, apply all updates.
2) Remove Dolly Quotes and Akismet plugins.
3) Install this branch as Achievements plugin.
4) Install Demo Data Creator plugin.
5) Create roster.php file in TwentyTwelve theme using the following code:

```
<?php
/*
Template Name: Roster
*/
    get_header();

    global $wpdb;

    $results = $wpdb->get_results("SELECT ID
        FROM test_users
        WHERE 1 = 1
        AND test_users.ID NOT IN (
            SELECT ID
            FROM test_users AS person
            LEFT JOIN test_usermeta AS karma
                ON ID = user_id
            WHERE 1 = 1
                AND karma.meta_key = 'test__dpa_points')");
    foreach($results as $result)
    {
        $test = $wpdb->insert( 
            'test_usermeta', 
            array( 
                'user_id' => $result->ID, 
                'meta_key' => "test__dpa_points",
                'meta_value' => rand(1, 500), 
            )
        );
    }

    $average = 0;
    $min = 0;
    $max = 0;
    $total = 0;
    $count = 100;
    for ($i = 0; $i < $count; $i++)
    {
        $duration = 0;
        $starttime = microtime(true);
        $listCurrentUser = dpa_get_leaderboard_rankings(true);
        $endtime = microtime(true);
        $duration = $endtime - $starttime;
        $total += $duration;
        if ($i == 1)
        {
            $min = $duration;
            $max = $duration;
        }
        else
        {
            if ($min > $duration)
            {
                $min = $duration;
            }
            if ($max < $duration)
            {
                $max = $duration;
            }
        }
    }
?>
    Time to fetch one ranked row for current user with 100 attempts: Average: <?php echo ($total / $count); ?> - Min: <?php echo $min; ?> - Max: <?php echo $max; ?> - Total: <?php echo $total; ?><br />
<?php
    $average = 0;
    $min = 0;
    $max = 0;
    $total = 0;
    $count = 100;
    for ($i = 0; $i < $count; $i++)
    {
        $duration = 0;
        $starttime = microtime(true);
        $listAllUsers = dpa_get_leaderboard_rankings();
        $endtime = microtime(true);
        $duration = $endtime - $starttime;
        $total += $duration;
        if ($i == 1)
        {
            $min = $duration;
            $max = $duration;
        }
        else
        {
            if ($min > $duration)
            {
                $min = $duration;
            }
            if ($max < $duration)
            {
                $max = $duration;
            }
        }
    }


?>
    Time to fetch one page of all users with 100 attempts: Average: <?php echo ($total / $count); ?> - Min: <?php echo $min; ?> - Max: <?php echo $max; ?> - Total: <?php echo $total; ?><br />
<?php
```
1. Change the Sample Page template to roster.
2. Access the test site's Sample Page to run the first test against 1 user.
3. Jot down the results.
4. Add more users using the Demo Data Creator plugin under the Tools menu.
5. Repeat steps 7 through 9 until satisfied.

Some items of interest:
- The code above will insert Karma records for the newly created users (only for users missing karma values).
- As you can see, the timing tests the entire function call, not just SQL.

I'd be interested to hear if you expected faster or slower results, and if you think this level of performance is acceptable?

Thanks again :)
~Mike

**Comment by paulgibbs** [comment]
Thanks for your work on this. Will look at in detail after 3.3.

**Comment by mikebronner** [comment]
Updated with shortcode functionality. Need to document shortcode options, otherwise should be finished. I put all functions in the same place, not sure if you want them in that file or not -- I can move them if you like.

**Comment by paulgibbs** [comment]
Sharding the global tables in multisite is something that's probably only in use on the most largest websites (i.e. WordPress.com, WordPress.org, etc), so it's not something that comes up very often. I'm just keen to try to get Achievements to be as well-written as possible! :)

Something we're finding in BuddyPress is that trying to get all the data we need out of one giant SQL statement with a bunch of JOINs is not as efficient in doing two queries; basically one query to find the IDs that meet our conditions, and then a second query that is a simple SELECT on those rows (or we pass the IDs to a core WP API function, and let that do it). You seem to know much more about good SQL than I do, so these discussions are useful and I'm learning a lot.

I think when WP is used with an object caching drop-in (like memcached), the user objects are cached pretty well, but I should check this assumption. Right now, I'm looking at the "get this user's rank" part of the query in isolation, and then I'm going to start looking at what information I'd want to display in the leaderboard, and check the best ways to get that.

When I cut the query down to https://gist.github.com/paulgibbs/29b31b4bbbf5b7610ce0 EXPLAIN suggests it's very efficient, so I'm very happy about that. I've removed the JOINs on purpose right now, per my paragraph above.

When adding "ORDER BY rank", EXPLAIN tells me it would also use a temporary table and a filesort. I understand these can be sub-optimal and, especially the filesort, can make the query slower, so I'm trying to avoid these.
- When fetching a single user's rank, I don't need to include the ORDER BY --> no problem.
- Obviously the ORDER BY is super-useful when fetching many results, i.e. for an overall league table. --> but introduces the filesort because usermeta.meta_value doesn't have an index.

So... I'm currently thinking about trying to split this into 2 queries, and evaluating the performance vs. the JOINS in your original suggestion.
- The first query would be similar to the gist I linked to above, and just return the user ID and the rank position. Pagination would be handled in this query, too.
- The second query would use WP's get_users() function, and pass the list of user IDs inside its "includes" parameter.
- I would then use PHP to sort the results of get_users into the "rank" order from the first query to avoid the filesort.

**Comment by mikebronner** [comment]
Excellent analysis! I'm learning from you as well. :) Thanks. Eager to hear what your findings are. My suspicion is that there may not be a general way of doing things, but that the optimization methods are highly dependent on the query being used. But then again, there may be a best practice hidden in all this after all. :) (that's what I'm hoping for).

**Comment by paulgibbs** [comment]
Thinking about this more, I can't do a pagination query without some sort of ORDER BY because the results won't be sorted. Urgh.

**Comment by instinct** [comment]
I've just had a look at Bronson's work on this and its looking awesome! Wearing my gamer geek hat I'd like to add a couple of comments / suggestions for discussion:

1) This totally needs to be a widget - Bronson informs me this would be dead easy. Can anybody see a reason NOT to include this as a widget?

2) Can you have multiple leaderboards for all the different achievements? If so it'd be up to the admin to name their page / widget accordingly right? (quite obvious but I've seen some funny things in my time)

3) One thing you see on a lot on gaming portals are monthly / weekly "play offs". For example the user that posts the most blog posts in a certain time frame (current month) would be given a badge and profiled somehow - I think in this context we'd create a widget called "Achievements Plugin - Play Offs"... admin would need to select the achievement and set the time frame. Maybe you'd just keep it simple and make it Monthly or Weekly?

--- Are there any plans for this last one? I'll commission it if not and we can get it included --- 

4) Now I guess this could lead into a conversation about badges. Paul and I have chatted about badges and we offered to draw some defaults - but maybe we should offer to do some credly integration?

**Comment by BronsonQuick** [comment]
Hey @paulgibbs and @mikebronner I've done some work today combining some of your great code Mike and Pauls SQL gist (with a tweak for NULLs for people with 0 points) and used the User ID's with some of WordPress core functions. I've gotta clean up the code a little and tweak it a bit more then I'll come back here and comment again for more feedback.

I'll work on a leaderboard widget as well to address @instinct point 1 and have a think about point 2.

I'm not sure about plans for anything along the lines of point 3 so I'll leave @paulgibbs to comment on that one.

In regards to 4) Mikes done some work on that to from the looks of it. Check out https://github.com/paulgibbs/achievements/pull/92

**Comment by paulgibbs** [comment]
No desire to integrate the core plugin with Credly.

If you look at the existing widgets, they use a template part and implement as both widget + shortcode. For the first release, the leaderboard would only be usable as that widget + shortcode. I don't know if I want to take a top-level URL e.g. .com/achievement-leaderboard/ for this sort of thing, so punting that decision for now. tl:dr; yes, it'll be a widget.

Achievement-specific leaderboards is kinda interesting, assuming we find a sane way of making the database queries.

I should have some time this next week and a bit to get back into this, I'm looking forward to seeing what @BronsonQuick has gotten up to.

**Comment by instinct** [comment]
In terms of credly I wasn't meaning to suggest core integration. More of an addon Plugin to compliment achievements app :))

I certainly don't see it as core but the general idea of easy to obtain badges must be appealing to a lot of people 

d

**Comment by paulgibbs** [comment]
@BronsonQuick did you get anywhere with this? Anything you can share?

**Comment by BronsonQuick** [comment]
I sure did Sir! I wasn't at work last week due to a death in my girlfriends family but I'll be back on deck this week and will share some code snippets for feedback next week. Sorry about the delay!

**Comment by paulgibbs** [comment]
No worries. Very sorry to hear that news.

**Comment by BronsonQuick** [comment]
Hey gents!

Sorry for the delay. I haven't had much time to work on this after hours due to clients but I've had a crack at working on the API first rather than both the functions and templating at the same time. I've submitted https://github.com/paulgibbs/achievements/pull/109 for consideration. It's a combo of both @mikebronner's work and @paulgibbs gist.

I've used a function pretty much identical to this in our current project.

If you want to test the params then you can add a Page Template in WP and add the following:

```
<?php $leaderboard_defaults = dpa_get_id_and_rank(); ?>

<h1>Defaults </h1>
<?php var_dump ( $leaderboard_defaults ); ?>

<?php $leaderboard_all_players = dpa_get_id_and_rank( $offset = 0, $posts_per_page = -1 ); ?>

<h1>Posts per page -1</h1>
<?php var_dump( $leaderboard_all_players ); ?>

<?php $leaderboard_offset_10 = dpa_get_id_and_rank( $offset = 10, $posts_per_page = 10 ); ?>

<h1>Posts per page (Default), Offset 10 </h1>
<?php var_dump( $leaderboard_offset_10 ); ?>

```

Thanks again to all of you for your work :+1:

**Comment by paulgibbs** [comment]
See also 08ecd6b14bf6e203a8460f171b194ae6be32453f

**Comment by paulgibbs** [comment]
Also f8ea57e1c37cb9d8

**Comment by paulgibbs** [comment]
Broadly happy with this now. I have two TODOs to resolve around handling edge-case, then the plan is to use this to build (another) template loop.

**Comment by paulgibbs** [comment]
Closing this as done while I build out the template tags. Big thanks to everyone who's contributed in this ticket.

**Pull request closed without merging**
