### PR TITLE
Achievement Admin Page With Thumbnails

### PR DESCRIPTION
**Pull request by mikebronner**
I have added the code necessary to show thumbnails in the admin page. Below is a preview of what it might look like. Disregard the Category columns as that is not part of this functionality.

The thumbnail header is not sortable at this time -- I didn't think sorting by image made sense.

Added comments in two places where changes can be made, theoretically in a Settings page if a UI were to be added in the future. One for column placement (default is 2nd), other for header title (default is Badge).

Thumbnail size is set to 39px to fit in current row heigh, but can be made larger without any problem.

### CODE REVIEW

**Comment by mikebronner** [comment]
Sorry for the massive amounts of reverts ... this was my first pull request, so I wanted to do it right and make a branch on my side for the change, so I can make other branches for other changes, instead of making the changes to the master.

**Comment by paulgibbs** [comment]
Was this intentionally closed?

**Comment by mikebronner** [comment]
Initially closed because I wanted to integrate this code directly into your existing functions, but changed my mind. Splitting this out into separate functions allows for more customization down the road.

**Comment by paulgibbs** [comment]
Can you squash those reverted commits together; or close this pull request, create a new branch, make a single commit, then pull from that?

**Comment by mikebronner** [comment]
I tried but couldn't figure out how … I'll keep looking.

~Mike

**Comment by mikebronner** [comment]
Too many screwy reverts. Resetting master fork to get rid of reverts and will resubmit pull request from branch.

**Pull request closed without merging**
